---
title: "RNG Production in Canada"
author: "Oscar Jaimes"
output:
  html_document:
    code_folding: hide
format: 
  html:
    code-fold: true
    page-layout: "full"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F,warning=F)
options(scipen = 999)

library(shiny)
library(shinydashboard)
library(kableExtra)
library(readxl)
library(janitor)
library(tidyverse)
library(lubridate)
library(scales)
library(viridis)
library(cansim)
library(cowplot)
library(gridExtra)
library(wesanderson)
library(ggplot2)
```


```{r, include=TRUE}
facility_production <- read_csv("facility_production.csv")
facility_production <- facility_production %>% 
  clean_names () %>% 
  mutate(province=fct_relevel(province,"BC","AB", "ON","QC"))
  
  
facility_production_prov <- facility_production %>%
  group_by(in_service_date, province) %>%
  filter(in_service_date > 2010)%>%
  summarize(
    stated_capacity_petajoules_year_prov = sum(stated_capacity_petajoules_year)
  )
```


```{r, include=TRUE}
energy_production <- read_csv("energy_production.csv")
energy_production <- energy_production %>% 
  clean_names ()
  
  
energy_production
energy_production <- energy_production %>%
  filter(fuel_type == "Renewable fuels") %>%
  filter(supply_and_demand_characteristics %in% c("Production", "Exports"))


energy_production %>%
  ggplot()+ #make a graph
  geom_line(aes(ref_date,value,group=supply_and_demand_characteristics,color=supply_and_demand_characteristics),linewidth=1.25)+
  guides(fill=guide_legend(nrow=1, title=NULL))+
  theme(
    text = element_text(size=16),
    legend.position = "bottom",
    plot.caption = element_text(hjust = 0, vjust = 1, face="italic"),
  )+
  labs(
    y="Terajoules",
    x="",
  )
```

## {.tabset}

### Production

```{r, fig.width=7, fig.height=4}
capacity_by_fuel <- facility_production %>%
  ggplot()+
  geom_col(
    aes(in_service_date,stated_capacity_petajoules_year,fill=type),
    position = "stack",
    colour="black",
    linewidth=0.0
  )+
  scale_fill_manual(values=viridis(n=8))+
  theme_minimal()+
  scale_y_continuous(
    expand=c(0,0),
  )+
  scale_x_continuous(
    breaks=pretty_breaks(),
  )+
  guides(fill=guide_legend(nrow=1, title=NULL))+
  theme(
    text = element_text(size=16),
    legend.position = "bottom",
    plot.caption = element_text(hjust = 0, vjust = 1, face="italic"),
  )+
  labs(
    y="Stated Capacity, Petajoules/Year",
    x="",
  )

capacity_by_prov <- energy_production %>%
  ggplot()+
  geom_line(
    data=energy_production,
    aes(ref_date,value, color="red"),
    linewidth=.85, ww="21"
  )


# Load Canada map data
canada_map <- map_data("world", region = "Canada")

# Prepare your locations data
# Replace these with your actual latitude and longitude
locations <- data.frame(
  name = c("Location1", "Location2"),
  lat = c(45, 56), # latitude
  long = c(-75, -106) # longitude
)

# Plot the map
canada_locations <- ggplot() +
  theme_void()+
  geom_polygon(data = canada_map, aes(x = long, y = lat, group = group), fill = "white", color = "black") +
  geom_point(data = locations, aes(x = long, y = lat), color = viridis(n=1), size = 3) +
  annotate("point", x = locations$long, y = locations$lat, colour = viridis(n=2, direction = -1), size = 4) +
  coord_fixed(1.3)+
  labs(
    title="RNG-Producing Locations in Canada, 2023",
  )

capacity_by_prov
```

### Geography
```{r, fig.width=12, fig.height=7}
# Load Canada map data
canada_map <- map_data("world", region = "Canada")

# Prepare your locations data
# Replace these with your actual latitude and longitude
locations <- data.frame(
  name = c("Location1", "Location2"),
  lat = c(45, 56), # latitude
  long = c(-75, -106) # longitude
)

# Plot the map
canada_locations <- ggplot() +
  theme_void()+
  geom_polygon(data = canada_map, aes(x = long, y = lat, group = group), fill = "white", color = "black") +
  geom_point(data = locations, aes(x = long, y = lat), color = "red", size = 3) +
  annotate("point", x = locations$long, y = locations$lat, colour = "red", size = 4) +
  coord_fixed(1.3)
```

## {-}



